filter:
    excluded_paths:
        - '*.min.js'
        - '*/dist/*'
        - 'vendor/*'
        - 'docs/*'
        - 'tools/*'
        - 'tests/*'
        - 'theme/default/bootstrap/*'
        - 'theme/default/dist/*'
        - 'theme/default/plugins/*'
tools:
    external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_pdepend: true
